# The map of Nigeria using Python program

""" Salau Nurudeen Oladehinbo, Tel:+2348023133091, e-mail: nsalau@yahoo.com
                                                                            """
import turtle
turtle.delay(50)
turtle.color("black" , "green")
turtle.penup()
turtle.goto(0, 0)
turtle.pendown()
turtle.begin_fill()
turtle.forward(100)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()

turtle.penup()
turtle.color("black" , "white")
turtle.goto(0, 0)
turtle.pendown()
turtle.begin_fill()
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.end_fill()

turtle.color("black" , "green")
turtle.penup()
turtle.goto(-100, 0)
turtle.pendown()
turtle.begin_fill()
turtle.left(180)
turtle.forward(100)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.end_fill()

turtle.penup()
turtle.color("black" , "")
turtle.goto(-200, -50)
turtle.pendown()
turtle.begin_fill()
turtle.right(90)
turtle.forward(250)
turtle.left(90)
turtle.forward(20)
turtle.left(90)
turtle.forward(250)
turtle.end_fill()

turtle.penup()
turtle.setposition(0,-300)
turtle.pendown()
turtle.write("THE MAP OF NIGERIA ")
turtle.done()


